name: Integration and Unit Tests for ITG

on:
  push:
    branches:
      - staging
      - stable


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -e .
    - name: Lint with flake8
      run: |
        python -m flake8 itg
        python -m flake8 tests
    - name: Test with unittest
      run: |
        # For now, only run unit tests (when we have time) since integration tests will cost money :P
        python -m unittest discover tests/unit_tests